const fs = require('fs');
const path = require('path');
const BASE = path.join('playground-vue', 'src', 'antd-vue');

const content = [
'<template>',
'  <div>',
'    <h2>撤销重做</h2>',
'    <p style="color: rgba(0,0,0,0.45); margin-bottom: 16px; font-size: 14px;">undo/redo 操作栈 / Ctrl+Z 撤销 / Ctrl+Shift+Z 重做</p>',
'    <PlaygroundForm :form="form">',
'      <template #default="{ mode }">',
'        <!-- 撤销 / 重做控制栏 -->',
'        <div style="display: flex; gap: 8px; align-items: center; margin-bottom: 16px">',
'          <button',
'            type="button"',
"            :disabled=\"!canUndo || mode !== 'editable'\"",
'            @click="undo"',
'            style="padding: 4px 15px; border: 1px solid #d9d9d9; border-radius: 6px; background: #fff; cursor: pointer; font-size: 14px"',
'          >撤销 (Ctrl+Z)</button>',
'          <button',
'            type="button"',
"            :disabled=\"!canRedo || mode !== 'editable'\"",
'            @click="redo"',
'            style="padding: 4px 15px; border: 1px solid #d9d9d9; border-radius: 6px; background: #fff; cursor: pointer; font-size: 14px"',
'          >重做 (Ctrl+Shift+Z)</button>',
'          <span style="display: inline-block; padding: 0 7px; font-size: 12px; line-height: 20px; border-radius: 4px; border: 1px solid #d9d9d9; background: #fafafa">',
'            历史：{{ historyIdx + 1 }} / {{ historyLen }}',
'          </span>',
'        </div>',
'',
'        <!-- 表单字段：自动渲染模式 -->',
'        <FormField v-for="n in FIELDS" :key="n" :name="n" :field-props="fieldSchemas[n]" />',
'      </template>',
'    </PlaygroundForm>',
'  </div>',
'</template>',
'',
'<script setup lang="ts">',
'/**',
' * 场景：撤销重做 - Field 模式（Ant Design Vue）',
' *',
' * 演示表单级别的 undo / redo 操作栈：',
' * - 每次值变化自动入栈（最多 50 条）',
' * - 支持按钮撤销 / 重做',
' * - 支持 Ctrl+Z / Ctrl+Shift+Z 快捷键',
' */',
"import type { FieldProps } from '@moluoxixi/core'",
"import { ref, computed, onMounted, onUnmounted } from 'vue'",
"import { FormField, useCreateForm } from '@moluoxixi/vue'",
"import { setupAntdVue } from '@moluoxixi/ui-antd-vue'",
"import PlaygroundForm from '../../components/PlaygroundForm.vue'",
'',
'setupAntdVue()',
'',
"const FIELDS = ['title', 'category', 'amount', 'note'] as const",
'',
'/** 最大历史记录条数 */',
'const MAX_HISTORY = 50',
'',
'/**',
' * 各字段的 schema 配置。',
" * wrapper 默认为 'FormItem'，无需显式声明。",
' */',
'const fieldSchemas: Record<string, Partial<FieldProps>> = {',
"  title: { label: '标题', required: true, component: 'Input' },",
"  category: { label: '分类', component: 'Input' },",
"  amount: { label: '金额', component: 'InputNumber', componentProps: { style: 'width: 100%' } },",
"  note: { label: '备注', component: 'Textarea', componentProps: { rows: 3 } },",
'}',
'',
"const form = useCreateForm({ initialValues: { title: '', category: '', amount: 0, note: '' } })",
'',
'/* ========== 撤销 / 重做状态 ========== */',
"const history = ref<Array<Record<string, unknown>>>([{ title: '', category: '', amount: 0, note: '' }])",
'const historyIdx = ref(0)',
'let isRestoring = false',
'',
'const historyLen = computed((): number => history.value.length)',
'const canUndo = computed((): boolean => historyIdx.value > 0)',
'const canRedo = computed((): boolean => historyIdx.value < history.value.length - 1)',
'',
'/* ========== 订阅值变化，自动入栈 ========== */',
'onMounted(() => {',
'  form.onValuesChange((v: Record<string, unknown>) => {',
'    if (isRestoring) return',
'    history.value = history.value.slice(0, historyIdx.value + 1)',
'    history.value.push({ ...v })',
'    if (history.value.length > MAX_HISTORY) history.value.shift()',
'    historyIdx.value = history.value.length - 1',
'  })',
'})',
'',
'/** 撤销：回退到上一条历史记录 */',
'function undo(): void {',
'  if (historyIdx.value <= 0) return',
'  historyIdx.value--',
'  isRestoring = true',
'  form.setValues(history.value[historyIdx.value])',
'  isRestoring = false',
'}',
'',
'/** 重做：前进到下一条历史记录 */',
'function redo(): void {',
'  if (historyIdx.value >= history.value.length - 1) return',
'  historyIdx.value++',
'  isRestoring = true',
'  form.setValues(history.value[historyIdx.value])',
'  isRestoring = false',
'}',
'',
'/** 键盘快捷键监听 */',
'function onKeyDown(e: KeyboardEvent): void {',
"  if (e.ctrlKey && e.key === 'z' && !e.shiftKey) { e.preventDefault(); undo() }",
"  if (e.ctrlKey && e.shiftKey && e.key === 'Z') { e.preventDefault(); redo() }",
'}',
'',
"onMounted(() => window.addEventListener('keydown', onKeyDown))",
"onUnmounted(() => window.removeEventListener('keydown', onKeyDown))",
'</script>',
'',
].join('\n');

fs.writeFileSync(path.join(BASE, 'UndoRedoForm', 'field.vue'), content, 'utf8');
console.log('UndoRedoForm/field.vue written successfully');
