# pnpm workspace 配置
# 用于管理 CLI 项目依赖版本

gitChecks: false
registry: https://registry.npmjs.org/

packages:
  - 'packages/*'
catalogs:
  build:
  dev:
    '@commitlint/cli': ^19.8.0
    '@commitlint/config-conventional': ^19.8.0
    '@moluoxixi/eslint-config': latest
    commitizen: ^4.3.1
    cz-customizable: ^7.4.0
    eslint: ^9.5.0
    husky: ^9.1.7
    jiti: ^2.4.2
    lint-staged: ^15.5.1
    tsx: ^4.20.5
    typescript: ~5.8.0
    vite: ^6.2.4
  type:
    '@types/fs-extra': ^11.0.4
    '@types/inquirer': ^9.0.7
    '@types/node': ^22.14.0
    '@vue-macros/volar': ^3.0.0-beta.15
