/* eslint-disable */
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus')['ElButton']
    ElDivider: typeof import('element-plus')['ElDivider']
    ElTabPane: typeof import('element-plus')['ElTabPane']
    ElTabs: typeof import('element-plus')['ElTabs']
  }
}
