<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { z } from 'zod'
import {
  ConfigForm,
  createFormRuntime,
  defineField,
} from '@moluoxixi/config-form'
import {
  createI18nPlugin,
  i18n,
  type I18nMessages,
} from '@moluoxixi/config-form-plugin-i18n'
import {
  ElInput,
  ElRadio,
  ElRadioGroup,
  ElSelectV2,
} from 'element-plus'

type Locale = 'zh-CN' | 'en-US'

const formRef = ref()
const formValues = reactive<Record<string, unknown>>({})
const locale = ref<Locale>('zh-CN')

const messages: I18nMessages = {
  'zh-CN': {
    'i18n.action.reset': '重置',
    'i18n.action.submit': '提交',
    'i18n.action.switchLocale': '切换到 {locale}',
    'i18n.action.validate': '校验',
    'i18n.custom.placeholder': '由 translate 自定义生成 label',
    'i18n.email.invalid': '请输入有效邮箱',
    'i18n.email.label': '邮箱',
    'i18n.email.placeholder': '请输入邮箱',
    'i18n.feedback.submitSuccess': '提交成功！',
    'i18n.feedback.validationFailed': '校验失败：',
    'i18n.gender.female': '女',
    'i18n.gender.label': '性别',
    'i18n.gender.male': '男',
    'i18n.gender.other': '其他',
    'i18n.locale.en': 'English',
    'i18n.locale.zh': '中文',
    'i18n.phone.label': '手机号（fallbackLocale）',
    'i18n.preview.title': '实时值（v-model）',
    'i18n.role.admin': '管理员',
    'i18n.role.guest': '访客',
    'i18n.role.label': '角色',
    'i18n.role.placeholder': '请选择角色',
    'i18n.role.required': '请选择角色',
    'i18n.role.user': '用户',
    'i18n.suggestion.label': (_params, context) => context.locale === 'en-US' ? 'Suggestion' : '建议',
    'i18n.suggestion.placeholder': '函数消息 label + token placeholder',
    'i18n.username.guestMin': '访客用户名至少 {min} 个字符',
    'i18n.username.label': '用户名（{min}-{max} 个字符）',
    'i18n.username.max': '用户名最多 {max} 个字符',
    'i18n.username.min': '用户名至少 {min} 个字符',
    'i18n.username.noSpace': '用户名不能包含空格',
    'i18n.username.placeholder': '请输入用户名',
  },
  'en-US': {
    'i18n.action.reset': 'Reset',
    'i18n.action.submit': 'Submit',
    'i18n.action.switchLocale': 'Switch to {locale}',
    'i18n.action.validate': 'Validate',
    'i18n.custom.placeholder': 'Label is generated by custom translate',
    'i18n.email.invalid': 'Please enter a valid email',
    'i18n.email.label': 'Email',
    'i18n.email.placeholder': 'Enter email',
    'i18n.feedback.submitSuccess': 'Submitted!',
    'i18n.feedback.validationFailed': 'Validation failed:',
    'i18n.gender.female': 'Female',
    'i18n.gender.label': 'Gender',
    'i18n.gender.male': 'Male',
    'i18n.gender.other': 'Other',
    'i18n.locale.en': 'English',
    'i18n.locale.zh': '中文',
    'i18n.preview.title': 'Live value (v-model)',
    'i18n.role.admin': 'Admin',
    'i18n.role.guest': 'Guest',
    'i18n.role.label': 'Role',
    'i18n.role.placeholder': 'Select role',
    'i18n.role.required': 'Select a role',
    'i18n.role.user': 'User',
    'i18n.suggestion.label': (_params, context) => context.locale === 'en-US' ? 'Suggestion' : '建议',
    'i18n.suggestion.placeholder': 'Function message label + token placeholder',
    'i18n.username.guestMin': 'Guest username must be at least {min} characters',
    'i18n.username.label': 'Username ({min}-{max} chars)',
    'i18n.username.max': 'Username must be at most {max} characters',
    'i18n.username.min': 'Username must be at least {min} characters',
    'i18n.username.noSpace': 'Username cannot contain spaces',
    'i18n.username.placeholder': 'Enter username',
  },
}

function renderTemplate(template: string, params?: Record<string, unknown>) {
  return template.replace(/\{([^}]+)\}/g, (_, key: string) => {
    const value = params?.[key.trim()]
    return value == null ? '' : String(value)
  })
}

function t(key: string, fallback: string, params?: Record<string, unknown>) {
  const message = messages[locale.value]?.[key] ?? messages['zh-CN']?.[key]
  return renderTemplate(typeof message === 'string' ? message : fallback, params)
}

const runtime = createFormRuntime({
  extensions: [
    createI18nPlugin({
      fallbackLocale: 'zh-CN',
      locale: () => locale.value,
      messages,
      translate: (key, params, fallback, context) => {
        if (key === 'i18n.custom.label') {
          const prefix = context.locale === 'en-US' ? 'Custom field' : '自定义字段'
          return `${prefix}: ${params?.field ?? context.field?.field ?? fallback ?? key}`
        }
        return undefined
      },
      missing: key => locale.value === 'en-US' ? `Untranslated: ${key}` : `未翻译：${key}`,
    }),
  ],
})

const nextLocaleLabel = computed(() => locale.value === 'zh-CN'
  ? t('i18n.locale.en', 'English')
  : t('i18n.locale.zh', '中文'))

const fields = computed(() => [
  defineField({
    field: 'username',
    label: i18n('i18n.username.label', '用户名', { max: 20, min: 2 }),
    validateOn: ['blur', 'change'],
    schema: z.string()
      .min(2, t('i18n.username.min', '用户名至少 {min} 个字符', { min: 2 }))
      .max(20, t('i18n.username.max', '用户名最多 {max} 个字符', { max: 20 })),
    span: 12,
    component: ElInput,
    props: { clearable: true, placeholder: i18n('i18n.username.placeholder', '请输入用户名') },
    validator: (value, values) => {
      if (values.role === 'guest' && value.length < 4)
        return t('i18n.username.guestMin', '访客用户名至少 {min} 个字符', { min: 4 })

      return value.includes(' ') ? t('i18n.username.noSpace', '用户名不能包含空格') : undefined
    },
    transform: value => value.trim(),
  }),
  defineField({
    field: 'email',
    label: i18n('i18n.email.label', '邮箱'),
    validateOn: 'blur',
    schema: z.string().email(t('i18n.email.invalid', '请输入有效邮箱')).optional(),
    span: 12,
    component: ElInput,
    props: { clearable: true, placeholder: i18n('i18n.email.placeholder', '请输入邮箱') },
    transform: value => value?.trim(),
  }),
  defineField({
    field: 'role',
    label: i18n('i18n.role.label', '角色'),
    schema: z.string().min(1, t('i18n.role.required', '请选择角色')).optional(),
    span: 12,
    component: ElSelectV2,
    props: {
      clearable: true,
      options: [
        { label: i18n('i18n.role.admin', '管理员'), value: 'admin' },
        { label: i18n('i18n.role.user', '用户'), value: 'user' },
        { label: i18n('i18n.role.guest', '访客'), value: 'guest' },
      ],
      placeholder: i18n('i18n.role.placeholder', '请选择角色'),
    },
  }),
  defineField({
    field: 'phone',
    label: i18n('i18n.phone.label', '手机号'),
    schema: z.string().optional(),
    span: 12,
    component: ElInput,
    props: { clearable: true, placeholder: i18n('i18n.phone.placeholder', '当前语言缺失时使用 fallback 文案') },
  }),
  defineField({
    field: 'gender',
    label: i18n('i18n.gender.label', '性别'),
    schema: z.string().optional(),
    span: 12,
    component: ElRadioGroup,
    slots: {
      default: [
        { component: ElRadio, props: { value: 'male' }, slots: { default: i18n('i18n.gender.male', '男') } },
        { component: ElRadio, props: { value: 'female' }, slots: { default: i18n('i18n.gender.female', '女') } },
        { component: ElRadio, props: { value: 'other' }, slots: { default: () => i18n('i18n.gender.other', '其他') } },
      ],
    },
  }),
  defineField({
    field: 'suggestion',
    label: i18n('i18n.suggestion.label', '建议'),
    schema: z.string().optional(),
    span: 12,
    component: ElInput,
    props: { clearable: true, placeholder: i18n('i18n.suggestion.placeholder', '请输入建议') },
  }),
  defineField({
    field: 'custom',
    label: i18n('i18n.custom.label', '自定义字段', { field: 'custom' }),
    schema: z.string().optional(),
    span: 12,
    component: ElInput,
    props: { clearable: true, placeholder: i18n('i18n.custom.placeholder', '自定义 translate') },
  }),
  defineField({
    field: 'missing',
    label: i18n('i18n.missing.label'),
    schema: z.string().optional(),
    span: 12,
    component: ElInput,
    props: { clearable: true, placeholder: i18n('i18n.missing.placeholder') },
  }),
])

function toggleLocale() {
  locale.value = locale.value === 'zh-CN' ? 'en-US' : 'zh-CN'
}

function onSubmit(values: Record<string, unknown>) {
  alert(`${t('i18n.feedback.submitSuccess', '提交成功！')}\n${JSON.stringify(values, null, 2)}`)
}

function onError(errors: Record<string, string[]>) {
  console.error(t('i18n.feedback.validationFailed', '校验失败：'), errors)
}

function onModelUpdate(vals: Record<string, unknown>) {
  Object.assign(formValues, vals)
}
</script>

<template>
  <div>
    <ConfigForm
      ref="formRef"
      :model-value="formValues"
      namespace="moluoxixi"
      :fields="fields"
      :runtime="runtime"
      label-width="120px"
      @submit="onSubmit"
      @error="onError"
      @update:model-value="onModelUpdate"
    />

    <div class="demo-actions">
      <el-button @click="toggleLocale">
        {{ t('i18n.action.switchLocale', '切换到 {locale}', { locale: nextLocaleLabel }) }}
      </el-button>
      <el-button type="primary" @click="formRef?.submit()">
        {{ t('i18n.action.submit', '提交') }}
      </el-button>
      <el-button @click="formRef?.validate()">
        {{ t('i18n.action.validate', '校验') }}
      </el-button>
      <el-button @click="formRef?.reset()">
        {{ t('i18n.action.reset', '重置') }}
      </el-button>
    </div>

    <el-divider>{{ t('i18n.preview.title', '实时值（v-model）') }}</el-divider>
    <pre class="value-preview">{{ JSON.stringify(formValues, null, 2) }}</pre>
  </div>
</template>

<style lang="scss">
.demo-actions {
  margin-top: 16px;
  display: flex;
  gap: 8px;
}

.value-preview {
  background: #f5f7fa;
  border: 1px solid #e4e7ed;
  border-radius: 4px;
  padding: 12px 16px;
  font-size: 12px;
  line-height: 1.6;
  max-height: 300px;
  overflow: auto;
}
</style>
