<script setup lang="ts">
import type { ConfigFormExpose, FormRuntimeOptions } from '@moluoxixi/config-form'
import { computed, reactive, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { z } from 'zod'
import {
  ConfigForm,
  defineField,
} from '@moluoxixi/config-form'
import { createAntdVuePlugin } from '@moluoxixi/config-form-plugin-antd-vue'
import Input from 'ant-design-vue/es/input'
import Radio, { RadioGroup } from 'ant-design-vue/es/radio'
import Select from 'ant-design-vue/es/select'

type Locale = 'zh-CN' | 'en-US'
type I18nFormValues = Record<string, unknown>

const formRef = ref<ConfigFormExpose<I18nFormValues>>()
const formValues = reactive<I18nFormValues>({})

const messages = {
  'zh-CN': {
    action: {
      reset: '重置',
      submit: '提交',
      switchLocale: '切换到 {locale}',
      validate: '校验',
    },
    custom: {
      label: '自定义字段',
      placeholder: '由 vue-i18n 生成 label',
    },
    email: {
      invalid: '请输入有效邮箱',
      label: '邮箱',
      placeholder: '请输入邮箱',
    },
    feedback: {
      submitSuccess: '提交成功！',
      validationFailed: '校验失败：',
    },
    gender: {
      female: '女',
      label: '性别',
      male: '男',
      other: '其他',
    },
    locale: {
      en: 'English',
      zh: '中文',
    },
    phone: {
      label: '手机号',
      placeholder: '请输入手机号',
    },
    preview: {
      title: '提交值快照',
    },
    role: {
      admin: '管理员',
      guest: '访客',
      label: '角色',
      placeholder: '请选择角色',
      required: '请选择角色',
      user: '用户',
    },
    suggestion: {
      label: '建议',
      placeholder: '字段文案由应用层 vue-i18n 生成',
    },
    username: {
      guestMin: '访客用户名至少 {min} 个字符',
      label: '用户名',
      max: '用户名最多 {max} 个字符',
      min: '用户名至少 {min} 个字符',
      noSpace: '用户名不能包含空格',
      placeholder: '请输入用户名',
    },
  },
  'en-US': {
    action: {
      reset: 'Reset',
      submit: 'Submit',
      switchLocale: 'Switch to {locale}',
      validate: 'Validate',
    },
    custom: {
      label: 'Custom field',
      placeholder: 'Label is generated by vue-i18n',
    },
    email: {
      invalid: 'Please enter a valid email',
      label: 'Email',
      placeholder: 'Enter email',
    },
    feedback: {
      submitSuccess: 'Submitted!',
      validationFailed: 'Validation failed:',
    },
    gender: {
      female: 'Female',
      label: 'Gender',
      male: 'Male',
      other: 'Other',
    },
    locale: {
      en: 'English',
      zh: '中文',
    },
    phone: {
      label: 'Phone',
      placeholder: 'Enter phone number',
    },
    preview: {
      title: 'Submitted value snapshot',
    },
    role: {
      admin: 'Admin',
      guest: 'Guest',
      label: 'Role',
      placeholder: 'Select role',
      required: 'Select a role',
      user: 'User',
    },
    suggestion: {
      label: 'Suggestion',
      placeholder: 'Field text is generated by app-level vue-i18n',
    },
    username: {
      guestMin: 'Guest username must be at least {min} characters',
      label: 'Username',
      max: 'Username must be at most {max} characters',
      min: 'Username must be at least {min} characters',
      noSpace: 'Username cannot contain spaces',
      placeholder: 'Enter username',
    },
  },
}

const {
  locale: i18nLocale,
  t: translateMessage,
  te,
} = useI18n({
  locale: 'zh-CN',
  messages,
  useScope: 'local',
})

const currentLocale = computed(() => i18nLocale.value as Locale)
const nextLocaleLabel = computed(() => currentLocale.value === 'zh-CN'
  ? t('locale.en')
  : t('locale.zh'))
const switchLocaleText = computed(() => t('action.switchLocale', { locale: nextLocaleLabel.value }))

const runtimeOptions = {
  plugins: [
    createAntdVuePlugin(),
  ],
} satisfies FormRuntimeOptions

/**
 * 读取当前 playground 的 vue-i18n 文案。
 *
 * 缺失 key 时直接抛错，避免 vue-i18n 默认返回 key 文本掩盖配置问题。
 */
function t(key: string, params?: Record<string, unknown>) {
  if (!te(key, currentLocale.value))
    throw new Error(`Missing playground i18n message: ${key}`)
  return params ? translateMessage(key, params) : translateMessage(key)
}

/**
 * 将空字符串归一化为 undefined。
 *
 * 仅用于示例中的可选文本字段，非字符串值保持原样交给 schema。
 */
function emptyStringToUndefined(value: unknown) {
  if (typeof value !== 'string')
    return value

  const trimmed = value.trim()
  return trimmed.length === 0 ? undefined : trimmed
}

/**
 * 创建可选文本 schema。
 *
 * 先把空字符串转为 undefined，再执行传入字符串 schema 的校验。
 */
function optionalText(schema: z.ZodString = z.string()) {
  return z.preprocess(emptyStringToUndefined, schema.optional())
}

const fields = computed(() => [
  defineField({
    field: 'username',
    label: t('username.label'),
    validateOn: ['blur', 'change'],
    schema: z.string()
      .min(2, t('username.min', { min: 2 }))
      .max(20, t('username.max', { max: 20 })),
    span: 12,
    component: Input,
    props: {
      allowClear: true,
      placeholder: t('username.placeholder'),
    },
    /**
     * 校验用户名与角色组合。
     *
     * 错误消息通过当前 locale 的 vue-i18n 文案生成。
     */
    validator: (value, values) => {
      if (values.role === 'guest' && value.length < 4)
        return t('username.guestMin', { min: 4 })

      return value.includes(' ') ? t('username.noSpace') : undefined
    },
    /** 提交前裁剪用户名空白，实时输入值保持不变。 */
    transform: value => value.trim(),
  }),
  defineField({
    field: 'email',
    label: t('email.label'),
    validateOn: 'blur',
    schema: optionalText(z.string().email(t('email.invalid'))),
    span: 12,
    component: Input,
    props: {
      allowClear: true,
      placeholder: t('email.placeholder'),
    },
    transform: emptyStringToUndefined,
  }),
  defineField({
    field: 'role',
    label: t('role.label'),
    schema: z.preprocess(emptyStringToUndefined, z.string().min(1, t('role.required')).optional()),
    span: 12,
    component: Select,
    props: {
      allowClear: true,
      options: [
        { label: t('role.admin'), value: 'admin' },
        { label: t('role.user'), value: 'user' },
        { label: t('role.guest'), value: 'guest' },
      ],
      placeholder: t('role.placeholder'),
    },
  }),
  defineField({
    field: 'phone',
    label: t('phone.label'),
    schema: optionalText(),
    span: 12,
    component: Input,
    props: {
      allowClear: true,
      placeholder: t('phone.placeholder'),
    },
    transform: emptyStringToUndefined,
  }),
  defineField({
    field: 'gender',
    label: t('gender.label'),
    schema: z.preprocess(emptyStringToUndefined, z.string().optional()),
    span: 12,
    component: RadioGroup,
    slots: {
      default: [
        defineField({
          component: Radio,
          props: { value: 'male' },
          slots: { default: defineField({ component: 'span', props: { textContent: t('gender.male') } }) },
        }),
        defineField({
          component: Radio,
          props: { value: 'female' },
          slots: { default: defineField({ component: 'span', props: { textContent: t('gender.female') } }) },
        }),
        defineField({
          component: Radio,
          props: { value: 'other' },
          slots: {
            default: defineField({ component: 'span', props: { textContent: t('gender.other') } }),
          },
        }),
      ],
    },
  }),
  defineField({
    field: 'suggestion',
    label: t('suggestion.label'),
    schema: optionalText(),
    span: 12,
    component: Input,
    props: {
      allowClear: true,
      placeholder: t('suggestion.placeholder'),
    },
    transform: emptyStringToUndefined,
  }),
  defineField({
    field: 'custom',
    label: t('custom.label'),
    schema: optionalText(),
    span: 12,
    component: Input,
    props: {
      allowClear: true,
      placeholder: t('custom.placeholder'),
    },
    transform: emptyStringToUndefined,
  }),
])

/**
 * 切换 playground 当前语言。
 *
 * locale 变化会触发表单字段 computed 重建，ConfigForm 只消费重建后的普通字段配置。
 */
function toggleLocale() {
  i18nLocale.value = currentLocale.value === 'zh-CN' ? 'en-US' : 'zh-CN'
}

/**
 * 展示 i18n 表单提交结果。
 *
 * 提交反馈文案使用当前 locale 的 vue-i18n 文案，不发起远端请求。
 */
function onSubmit(values: I18nFormValues) {
  Object.assign(formValues, values)
  alert(`${t('feedback.submitSuccess')}\n${JSON.stringify(values, null, 2)}`)
}

/**
 * 输出 i18n 表单校验失败结果。
 *
 * 错误前缀使用当前 locale，本体保持 ConfigForm 的字段错误结构。
 */
function onError(errors: Record<string, string[]>) {
  console.error(t('feedback.validationFailed'), errors)
}
</script>

<template>
  <div>
    <ConfigForm
      ref="formRef"
      :default-values="formValues"
      namespace="moluoxixi"
      :fields="fields"
      :runtime="runtimeOptions"
      label-width="120px"
      @submit="onSubmit"
      @error="onError"
    />

    <div class="demo-actions">
      <a-button @click="toggleLocale">
        {{ switchLocaleText }}
      </a-button>
      <a-button type="primary" @click="formRef?.submit()">
        {{ t('action.submit') }}
      </a-button>
      <a-button @click="formRef?.validate()">
        {{ t('action.validate') }}
      </a-button>
      <a-button @click="formRef?.reset()">
        {{ t('action.reset') }}
      </a-button>
    </div>

    <a-divider>{{ t('preview.title') }}</a-divider>
    <pre class="value-preview">{{ JSON.stringify(formValues, null, 2) }}</pre>
  </div>
</template>

<style lang="scss">
.demo-actions {
  margin-top: 16px;
  display: flex;
  gap: 8px;
}

.value-preview {
  background: #fafafa;
  border: 1px solid #d9d9d9;
  border-radius: 6px;
  padding: 12px 16px;
  font-size: 12px;
  line-height: 1.6;
  max-height: 300px;
  overflow: auto;
}
</style>
